tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "ansible"
brew "mackup"
brew "mas"
cask "alfred"
cask "anydesk"
cask "appcleaner"
cask "cheatsheet"
cask "clickup"
cask "discord"
cask "docker"
cask "downie"
cask "dropbox"
cask "github"
cask "gitkraken"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-drive-file-stream"
cask "iconjar"
cask "icons8"
cask "iina"
cask "iterm2"
cask "keka"
cask "liteicon"
cask "marked"
cask "numi"
cask "pdfelement"
cask "permute"
cask "prizmo"
cask "soda-player"
cask "tiles"
cask "transmission"
cask "unite"
cask "vagrant"
cask "viber"
cask "visual-studio-code"
cask "whatsapp"
cask "wrike"
cask "zoomus"
mas "Amphetamine", id: 937984704
mas "AudioNote - Notepad and Voice Recorder", id: 406393290
mas "iThoughtsX", id: 720669838
mas "Telegram", id: 747648890
mas "Todoist", id: 585829637
mas "Treenity", id: 1208520991
